window.PORTFOLIO_ITEMS = [
  {
    wrapperClass: "a",
    frontClass: "llm-prep",
    title: "Resolving component ambiguity",
    client: "HoneyBook",
    year: "2025",
  },
  {
    wrapperClass: "a",
    frontClass: "tokenization-prep",
    title: "Tokenization and system foundations",
    client: "HoneyBook",
    year: "2026",
  },
  {
    wrapperClass: "a",
    frontClass: "navigation",
    title: "Navigation for an ever-evolving structure",
    client: "NEXT",
    year: "2025",
  },
  {
    wrapperClass: "b",
    frontClass: "card",
    title: "Intuitive card selection",
    client: "NEXT",
    year: "2023",
  },
  {
    wrapperClass: "b",
    frontClass: "search",
    title: "Advanced dataset search",
    client: "NEXT",
    year: "2023",
  },
  {
    wrapperClass: "b",
    frontClass: "piechart",
    title: "Quantifiable customer insights",
    client: "NEXT",
    year: "2024",
  },
  {
    wrapperClass: "b",
    frontClass: "cluster-creation",
    title: "Visualized pattern finding",
    client: "NEXT",
    year: "2023",
  },
  {
    wrapperClass: "",
    frontClass: "chips",
    title: "Flexible accessible design system foundations",
    client: "NEXT",
    year: "2023",
  },
  {
    wrapperClass: "",
    frontClass: "meditation",
    title: "Beneficial communal meditation",
    client: "Human Phones",
    year: "2019",
  },
  {
    wrapperClass: "",
    frontClass: "integrations",
    title: "Integral data management tools",
    client: "NEXT",
    year: "2023",
  },
  {
    wrapperClass: "",
    frontClass: "cluster-load",
    title: "Dynamic data preview",
    client: "NEXT",
    year: "2024",
  },
  {
    wrapperClass: "",
    frontClass: "login",
    title: "Sign up experience",
    client: "NEXT",
    year: "2023",
  },
  {
    wrapperClass: "",
    frontClass: "prompt",
    title: "Customizable prompt shortcuts",
    client: "NEXT",
    year: "2023",
  },
  {
    wrapperClass: "",
    frontClass: "riskoverview",
    title: "Security risk prioritization",
    client: "Hadrian",
    year: "2021",
  },
  {
    wrapperClass: "",
    frontClass: "product-card",
    title: "Product card",
    client: "Spinn",
    year: "2022",
  },
  {
    wrapperClass: "",
    frontClass: "carouselui",
    title: "Intuitive option exploration",
    client: "Spinn",
    year: "2022",
  },
  {
    wrapperClass: "",
    frontClass: "checkreflect",
    title: "Reducing food waste",
    client: "Albert Heijn",
    year: "2019",
  },
];
